### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by johnsonjh** [misterblack1/plexus-p20#14]
Discord link expired, is there a new one?

**Comment by kittennbfive** [comment]
Looks like Adrian made a misstake while updating. The link https://discord.gg/kRrnvF4HSd does work it looks like, but the *text* is still pointing to the old URL.

**Comment by kittennbfive** [comment]
I have created a PR #20 so it will be fixed for people who copy the link manually.

**Comment by misterblack1** [comment]
Sorry about this -- it's fully fixed after the merge
