### ISSUE TITLE
Access to disc image

### ISSUE THREAD

**Issue by jegjessing** [misterblack1/plexus-p20#2]
Hi i'd like to attempt getting out som of the passwords. Maybe also try some old unx versions to mount the images.
They are not here is that in order to keep personal information hidden?

**Comment by polluks** [comment]
It's already been hacked `1/2pint` :-)

**Comment by misterblack1** [comment]
Hey there -- yes exactly there is PII in the drive image, so I have a few people helping sanitize it first. The format isn't something modern tools can easily mount and work with, so it's taking longer than expected. And indeed, the password was already reversed. When the drive image is clear of PII, I'll share it here.

**Comment by misterblack1** [comment]
Closed, for now
