### ISSUE TITLE
Please add the information for the P25 as well

### ISSUE THREAD

**Issue by Jibun-no-Kage** [misterblack1/plexus-p20#3]
Please add the information for the P25 as well...
[https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=http://www.bitsavers.org/pdf/plexus/brochures/Plexus_P25_Brochure_1982.pdf&ved=2ahUKEwi26New1KqGAxUPC0QIHRPeBzEQFnoECAkQAQ&usg=AOvVaw0oxDevzorxHM7klQ9jXt9E](javascript:void(0);)

**Comment by misterblack1** [comment]
That machine isn't relevant to the P/20 as it's the old Z8001 architecture. We'll need to clean up this repo or migrate it to something better once I'm done getting this machine working. (A plexus super repo?)

**Comment by Jibun-no-Kage** [comment]
Ah... that explains why you did not mention it in the video.  Interesting that the same company qualified to different architectures in apparently the same product line.  Not like that has not happened before however.
